[package]
name = "eb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "1.0.1"
clap = { version = "4.3.0", features = ["derive"] }
term_grid = "0.2"
term_size = "0.3.2"
